language: python

# Setup Python 3.5 on Travis
# https://github.com/travis-ci/travis-ci/issues/4794
python:
    - 3.5

env:
    matrix:
        - TOX_ENV=py27
        - TOX_ENV=py35

before_script:
    - pip install tox

script:
    - tox -e ${TOX_ENV}
